[build]
  command = "npm rebuild canvas --build-from-source && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  CANVAS_PREBUILT = "false"
